"""phase2

Revision ID: d6c8943a53a6
Revises: d0fe662f0550
Create Date: 2026-08-30 10:53:24.555459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd6c8943a53a6'
down_revision: Union[str, Sequence[str], None] = 'd0fe662f0550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('prompt_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_cache_id'), 'semantic_cache', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_cache_model'), 'semantic_cache', ['model'], unique=False)
    op.create_index(op.f('ix_semantic_cache_prompt_hash'), 'semantic_cache', ['prompt_hash'], unique=False)
    op.add_column('requests', sa.Column('complexity_score', sa.Float(), nullable=True))
    op.add_column('requests', sa.Column('compression_ratio', sa.Float(), nullable=True))
    op.add_column('requests', sa.Column('routing_tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'routing_tier')
    op.drop_column('requests', 'compression_ratio')
    op.drop_column('requests', 'complexity_score')
    op.drop_index(op.f('ix_semantic_cache_prompt_hash'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_model'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_id'), table_name='semantic_cache')
    op.drop_table('semantic_cache')
    # ### end Alembic commands ###
